// Code generated by automap. DO NOT EDIT.

//go:build !automap

//go:generate automap

package my

import (
	"automap/internal/_tests/02_getters/external"
)

func ValueToValue(user external.User) UserName {
	return UserName{
		FirstName: user.FirstName(),
		LastName: user.LastName(),
	}
}

func ValueToPtr(user external.User) *UserName {
	return &UserName{
		FirstName: user.FirstName(),
		LastName: user.LastName(),
	}
}

func PtrToValue(user *external.User) UserName {
	return UserName{
		FirstName: user.FirstName(),
		LastName: user.LastName(),
	}
}

func PtrToPtr(user *external.User) *UserName {
	return &UserName{
		FirstName: user.FirstName(),
		LastName: user.LastName(),
	}
}
