// Code generated by automap. DO NOT EDIT.

//go:build !automap

//go:generate automap

package my

import (
	"github.com/skhoroshavin/automap/tests/01_simple/external"
)

func ValueToValue(user external.User) UserName {
	return UserName{
		FirstName: user.FirstName,
		LastName: user.LastName,
	}
}

func ValueToPtr(user external.User) *UserName {
	return &UserName{
		FirstName: user.FirstName,
		LastName: user.LastName,
	}
}

func PtrToValue(user *external.User) UserName {
	return UserName{
		FirstName: user.FirstName,
		LastName: user.LastName,
	}
}

func PtrToPtr(user *external.User) *UserName {
	return &UserName{
		FirstName: user.FirstName,
		LastName: user.LastName,
	}
}
