package writer

import (
	"automap/internal/utils"
	"io"
)

const header = `// Code generated by automap. DO NOT EDIT.

//go:build !automap

//go:generate automap
`

func writeHeader(out io.StringWriter, packageName string) (err error) {
	err = utils.WriteLn(out, header)
	if err != nil {
		return
	}

	err = utils.WriteLn(out, "package %s", packageName)
	return
}
