package writer

import (
	"fmt"
	"io"
)

const header = `// Code generated by automap. DO NOT EDIT.

//go:build !automap

//go:generate automap

package %s
`

func writeOldHeader(out io.Writer, packageName string) (err error) {
	_, err = fmt.Fprintf(out, header, packageName)
	return
}
