// Code generated by automap. DO NOT EDIT.

//go:build !automap

//go:generate automap

package my

import (
	"github.com/skhoroshavin/automap/tests/03_flatten/external"
)

func ValueToValue(user external.User) UserDTO {
	return UserDTO{
		FirstName: user.FirstName,
		LastName: user.LastName,
		AddressCode: user.Address.Code,
		StreetAndCity: user.Address.StreetAndCity(),
		Country: user.Address.Country,
		PrefsGolang: user.Prefs().Golang,
		PrefsCompiled: user.Prefs().Compiled(),
	}
}
