// Code generated by automap. DO NOT EDIT.

//go:build !automap

//go:generate automap

package my

import (
	"automap/internal/_tests/01_simple/external"
)

func MapUserName(user *external.User) *UserName {
	return &UserName{
		FirstName: user.FirstName,
		LastName: user.LastName,
	}
}
